/**
* @file sct.h
*
* @brief sct timer with match compared output for beeper
*
* @version 1.0
*
* @date 2013-06-27
*
* @author  Hartmut Wendt  info@hwhardsoft.de	<http://www.hwhardsoft.de>
*
* @copyright GNU Public License V3
*
* @note
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef __SCT_H__
#define __SCT_H__

/* Generated by fzmparser version 2.2 --- DO NOT EDIT! */

#include "LPC8xx.h"

//#define delay (10000000)
//#define delay (1000)

extern void sct_init (void);
extern void beep_stop(void);
extern void beep_start(uint32_t value);

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_Output_pin_0 (0)
#define SCT_OUTPUTPRELOAD_Output_pin_0 (1)


/* Match register reload macro definitions */
#define reload_matchOnDelay(value) LPC_SCT->MATCHREL[0].U = value;



#endif
